package:
  name: atmos
  version: "0.2.4"    # version of package. Should use the PEP-386 verlib
                      # conventions. Note that YAML will interpret
                      # versions like 1.0 as floats, meaning that 1.0 will
                      # be the same as 1. To avoid this, always put the
                      # version in quotes, so that it will be interpreted
                      # as a string.

                      # The version cannot contain a dash '-' character.

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - six >=1.9.0
    - numexpr >=2.0.1
    - numpy >=1.6
    - nose >=1.3
    - setuptools >=15.0
    - cfunits >=1.0
    - scipy >=0.16.0
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  # Package names should be any valid conda spec (see "Specifying versions
  # in requirements" below).
  run:
    - python
    - six >=1.9.0
    - numexpr >=2.3.0
    - numpy >=1.6
    - nose >=1.3
    - setuptools >=15.0
    - pint >=0.6
    - cfunits >=1.0
    - scipy >=0.16.0

test:
  # in addition to the run-time requirements, you can specify requirements
  # needed during testing. The run time requirements specified above are
  # included automatically.
  #requires:
  #  - nose >=1.3
  # Python imports we want to make sure work, which we expect the package
  # to install
  imports:
    - atmos
  # The script run_test.sh (or .bat/.py/.pl) will be run automatically
  # if it is part of the recipe.
  # (.py/.pl scripts are only valid as part of Python/Perl packages, respectively)

about:
  home: https://github.com/mcgibbon/atmos.git
  license: MIT
  summary: an atmospheric sciences utility library
